spring.application.name=paddleup

server.servlet.context-path=/api/v1
server.port=8020

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2

#spring.jpa.hibernate.ddl-auto=none
#spring.jpa.properties.jakarta.persistence.schema-generation.scripts.action=create
#spring.jpa.properties.jakarta.persistence.schema-generation.scripts.create-target=target/schema.sql

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
#spring.flyway.validate-on-migrate=false
#spring.flyway.repair-on-migrate=true

